baseURL = 'https://smoliicek.cz'
languageCode = 'en-us'
author = 'Vít Smolík'
copyright = "© 2024, smoliicek.cz"
title = 'smoliicek - blog'
theme = "paper"

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'smoliiczech'               # twitter.com/YOUR_TWITTER_ID
  github = 'smajlll'                 # github.com/YOUR_GITHUB_ID
  instagram = 'smoliik.v'           # instagram.com/YOUR_INSTAGRAM_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = 'me@smoliicek.cz'                 # gravatar email or image url
  name = 'Vít Smolík'
  bio = 'Linux user, C++ developer, math guy, 🇨🇿'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
